In [1]:
import matplotlib.pyplot as plt
import pandas as pd
data_frame_Arrests_under_crime_against_women = pd.read_csv("Arrests_under_crime_against_women.csv")
data_frame_Arrests_under_crime_against_women.drop(labels="Group_Name", axis='columns', inplace=True)
print(data_frame_Arrests_under_crime_against_women.shape)
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(data_frame_Arrests_under_crime_against_women, test_size=0.25, random_state=94)
print("Train set no. of rows and columns ",train_set.shape)
print("Test set no. of rows and columns ",test_set.shape)

(4165, 15)
Train set no. of rows and columns  (3123, 15)
Test set no. of rows and columns  (1042, 15)


### Features for X and Y
I have chosed the year as a intial set of feature for x and Total_Persons_under_Trial as a target feature y to know how many people under trail form 2001 to 2010 and to predict the crime rate in the feature.

In [13]:
from sklearn.tree import DecisionTreeClassifier
X = train_set[["Year"]]
Y = train_set["Total_Persons_under_Trial"]
tree_classifier = DecisionTreeClassifier()
print(tree_classifier.fit(X,Y))
from sklearn.metrics import confusion_matrix
y_predicted = tree_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix")
print(matrix)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
print ("Accuracy: ", accuracy_score(Y, y_predicted))
print ("Sensitivity: ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision: ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1: ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
Confusion Matrix
[[841   0   0 ...   0   0   0]
 [ 56   0   0 ...   0   0   0]
 [ 47   0   0 ...   0   0   0]
 ...
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]]
Accuracy:  0.2692923471021454
Sensitivity:  0.2692923471021454
Precision:  0.2692923471021454
F1:  0.4243188698284561


### Results
1. Accuracy is 26% correct prediction from the input
2. Sensitivity and precision are 26% from the input

In [15]:
from sklearn.svm import SVC
X = train_set[["Year"]]
Y = train_set["Total_Persons_under_Trial"]
svm_classifier = SVC(gamma='auto')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix")
print(matrix)
print ("Accuracy: ", accuracy_score(Y, y_predicted))
print ("Sensitivity: ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision: ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1: ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Confusion Matrix
[[841   0   0 ...   0   0   0]
 [ 56   0   0 ...   0   0   0]
 [ 47   0   0 ...   0   0   0]
 ...
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]]
Accuracy:  0.2692923471021454
Sensitivity:  0.2692923471021454
Precision:  0.2692923471021454
F1:  0.4243188698284561


In [11]:
X = test_set[["Year"]]
Y = test_set["Total_Persons_under_Trial"]
svm_classifier = SVC(gamma='auto')
print(svm_classifier.fit(X,Y))
y_predicted = svm_classifier.predict(X)
matrix = confusion_matrix(Y, y_predicted)
print("Confusion Matrix")
print(matrix)
print ("Accuracy: ", accuracy_score(Y, y_predicted))
print ("Sensitivity: ", recall_score(Y, y_predicted, average="weighted"))
print ("Precision: ", precision_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))
print ("F1: ", f1_score(Y, y_predicted, average="weighted",labels=np.unique(y_predicted)))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Confusion Matrix
[[309   0   0 ...   0   0   0]
 [ 20   0   0 ...   0   0   0]
 [ 12   0   0 ...   0   0   0]
 ...
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]]
Accuracy:  0.2965451055662188
Sensitivity:  0.2965451055662188
Precision:  0.2965451055662188
F1:  0.4574389341228719


From the above classifiers, we have different accuracy results. The better the accuracy level the better the model.